### ISSUE TITLE
HitsIteractor showItemsOnEmptyQuery not working.

### ISSUE THREAD

**Issue by barbun** [algolia/instantsearch-ios-examples#12]
Hi,

I have been implementing the new v5 of InstantSearch in my app and cannot seem to get the _**showItemsOnEmptyQuery**_ parameter to make any difference.

Below is my setup:

```
class SearchViewController: UIViewController {
    
    let searcher: SingleIndexSearcher = SingleIndexSearcher(appID: "ID", apiKey: "AppKey", indexName: "IndexName")
    let queryInputInteractor: QueryInputInteractor = .init()
    var searchBarController: SearchBarController?

    var hitsInteractor: HitsInteractor<JSON> = .init(infiniteScrolling: .on(withOffset: 10), showItemsOnEmptyQuery: false)
    
    var results: [JSON] = []
    
    @IBOutlet var searchBar: UISearchBar!
    
    override func viewDidLoad() {
        // Init the controller with our search bar from storyboard.
        self.searchBarController = .init(searchBar: self.searchBar)

       // Notify searcher about query text changes and launch a new search
        queryInputInteractor.connectSearcher(searcher)

        // Update query text in interactor each time query text changed in a UISearchBar
        queryInputInteractor.connectController(self.searchBarController!)

        // Update hitsInteractor with up-to-date search results
        hitsInteractor.connectSearcher(searcher)
        hitsInteractor.onResultsUpdated.subscribe(with: self) { _, results in
          self.results = results.hits
          self.tableView.reloadData()
        }
   }
```

As you can see, I feed the _**UISearchBar**_ from the Storyboard to the searchBarController and then  leverage _**hitsInteractor.onResultsUpdated**_ method to collect the results. So far, everything works fine and I am able to successfully retrieve the results. 

However, when the search bar is empty, then onResultsUpdated returns all results, effectively ignoring the _**showItemsOnEmptyQuery: false**_ parameter that was set during init. 

Do you have any idea why the parameter is not being respected and how to prevent any results on empty query? 

Thanks in advance.

**Comment by barbun** [comment]
Just to mention, this does not seem to be the issue with the searchBar as I also tried the default search bar and faced the same issue.

`self.searchBarController = .init(searchBar: .init())`

**Comment by spinach** [comment]
Hi @barbun,

Thank you for contacting us. 

The reason it is not working is because the `showItemsOnEmptyQuery` is in effect when you use the hitsInteractor with a controller, since it is just presentation logic and not business logic. In your case, you're using the `onResultsUpdated` signal which is a low level API that gives you access to the raw search results, so you'll have to do the check manually. 

If you want to see how to use a hits controller, you can refer to our [hits docs](https://www.algolia.com/doc/api-reference/widgets/hits/ios/).

Let us know if you face any other issues!

**Comment by barbun** [comment]
@spinach thanks for your answer! I see...having looked into the actual usage of that parameter:

```
public func numberOfHits() -> Int {
    guard let hitsPageMap = paginator.pageMap else { return 0 }
    
    if isLastQueryEmpty && !settings.showItemsOnEmptyQuery {
      return 0
    } else {
      return hitsPageMap.count
    }
  }
```

It seems that the number of results is just returned as 0 when that parameter is `false`, even though there was a query run against the index and it returned the results. I would be nice to move this logic into the searcher itself to prevent the query to be run in a first place. Perhaps something for the roadmap? 

Thanks once again!

**Comment by spinach** [comment]
I totally agree with you, you're definitely right here! Indeed we have a task for that to optimise the number of requests, but really thanks for proposing this change :)

**Comment by leojkwan** [comment]
I ran into the same problem. @spinach I don't think that's a good expectation for `showItemsOnEmptyQuery`. I would assume the searcher prevents the initial query. Hope there is an update for this in the documentation.

**Comment by spinach** [comment]
Hello - Indeed, we'll make sure to prioritise this, as this should be high priority as you pointed out. Thank you for your patience!

**Comment by AdamBCo** [comment]
Any update on this issue?

**Comment by VladislavFitz** [comment]
Hello @AdamBCo. 

In the [v7.1.0](https://github.com/algolia/instantsearch-ios/releases/tag/7.1.0) of InstantSearch we introduced an optional [shouldTriggerSearch](https://github.com/algolia/instantsearch-ios/blob/8c9ab5329bcf84b407a0e5beb3959d748046f9c5/Sources/InstantSearchCore/Searcher/SingleIndex/SingleIndexSearcher.swift#L81) closure. You can set it to specify the condition for triggering/blocking a search. In the code documentation you can find how to block search for empty query. 

Sorry for not notifying you in a timely manner.
