### ISSUE TITLE
Demo build errors

### ISSUE THREAD

**Issue by aprato** [algolia/instantsearch-ios-examples#13]
With the current pod file cocoapods is unable to resolve dependancies. If I modify the podfile to remove the branches then the build fails.

**Comment by VladislavFitz** [comment]
Hey aprato,
Thank you for your remark. 
An update has been pushed. Now the project uses Swift Package Manager as a dependency manager, so the correct dependencies will be fetched automatically once the project opened in Xcode 11. 
The dependencies versions in the Podfile has been fixed as well, if you cannot use SPM for some reason, please checkout [the last commit with cocoapods compatibility](https://github.com/algolia/instantsearch-ios-examples/releases/tag/cocoapods-compatibility).
