### ISSUE TITLE
Use of undeclared type 'MatchingPattern'

### ISSUE THREAD

**Issue by vatsal1992** [algolia/instantsearch-ios-examples#14]
![Screenshot 2020-06-10 at 12 40 32 PM](https://user-images.githubusercontent.com/12713108/84237785-96c03d80-ab17-11ea-9cf4-7c36c9ee961b.png)
Deployment Target: iOS13
Swift Version : 5

**Comment by spinach** [comment]
Hi @vatsal1992 ,

Thanks for reporting this. If you go and do `File -> Swift Packages -> Update to Latest Package Versions`, it should solve your problem. 

Let us know if it doesn't!
