### ISSUE TITLE
Error: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0

### ISSUE THREAD

**Issue by fvvliet** [algolia/instantsearch-ios-examples#16]
Received errors when building this project in XCode 12.0.1:

"The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.0.99."

Please advice for a solution.

Thanks
Frank

**Comment by VladislavFitz** [comment]
Hello @fvvliet 
The project has been updated with the latest libraries version, so it's fully compatible with Xcode 12.
Try to fetch the latest changes from master.
