### ISSUE TITLE
SwiftUI demo?

### ISSUE THREAD

**Issue by alelordelo** [algolia/instantsearch-ios-examples#19]
Any SwiftUI demo available?

**Comment by alelordelo** [comment]
Update:

Found the SwiftUI example by @VladislavFitz , but getting this error on build:

'notifyForInfiniteScrolling' is inaccessible due to 'fileprivate' protection level

Anyone ran into same issue, or know of another SwiftUI example?

**Comment by VladislavFitz** [comment]
Hi @alelordelo,

The existing SwiftUI demo is a prototype and is not a recommended implementation. The work on SwiftUI integration is in active progress. I just published a [SwiftUI branch]([https://github.com/algolia/instantsearch-ios/tree/feat/swiftui]) in the InstantSearch repository that will make this prototype compile. You can use this branch in your project in the meantime. Don't hesitate to communicate any issues/requests in the [issues section](https://github.com/algolia/instantsearch-ios/issues) of this repository.
