### ISSUE TITLE
RefinementList search controller

### ISSUE THREAD

**Issue by agathe** [algolia/instantsearch-ios-examples#2]
Testing the ecommerce example with iOS 10: 

In the ecommerce app, the `UISearchController` created in the filter view controllers for type and categories) does not filter the list. 
Is there something missing to connect it to search for facets?

If I use `InstantSearch.shared.register(searchController: searchController)` , it seems like it's filtering the records, not the facets.

https://github.com/algolia/instantsearch-ios-examples/blob/0bf1196211c2e86131d297d0fc78fcb85cfd52fc/ecommerce%20Ikea/ecommerce/TypeFacetTableViewController.swift#L22

**Comment by spinach** [comment]
Hi @agathe,

Thank you for contacting us and sorry for the late reply on that one. 
You are definitely right, I should have removed the SearchBar from that screen. 

We do support search for facet values on the [Algolia API Client level](https://github.com/algolia/algoliasearch-client-swift/blob/52c5266547f06dc6b2bddaa94542e8828aaa9544/Sources/AlgoliaSearch-Client/Index.swift#L407) but not yet on the InstantSearch level (we forgot to remove the search bar from the type screen). We will add a widget specifically for that in the near future. Does that sound something like you would be using? 

By the way we'd love to hear about your specific use cases and your feedback on InstantSearch 🙂 

Sorry about the confusion
