### ISSUE TITLE
Around Precision property has issue , when It assigned gives code 400 error

### ISSUE THREAD

**Issue by vishalgspaceo** [algolia/instantsearch-ios-examples#28]
When I try to assign a property called **aroundPrecision** , Query Response throws an error with code 400

I checked by assigning as below 
`searcher.request.query.aroundPrecision = [.init(integerLiteral: 1000)]
`

Request of Query Would be 
`&aroundLatLng=23.0321,72.5252&aroundRadius=50000&aroundPrecision=%5B%7B%22from%22:0.0,%22value%22:1000.0%7D%5D`

Response of Query Would be 
```
{
  "message" : "Invalid value for \"aroundPrecision\" parameter, expected valid JSON (Expecting an integer (near 1:13))",
  "status" : 400
}
```
I would love to know the solution of above problem

**Comment by vishalgspaceo** [comment]
@valentindotxyz  is there any update on this issue ?

**Comment by VladislavFitz** [comment]
Hi @vishalgspaceo,
Thank you for reporting this. 
It is basically the Swift API client issue, so I move your report [there](https://github.com/algolia/algoliasearch-client-swift/issues/763). I will investigate it in the coming days.
