### ISSUE TITLE
Query suggestions lacks a GIF in the docs

### ISSUE THREAD

**Issue by PLNech** [algolia/instantsearch-ios-examples#6]
[![image](https://user-images.githubusercontent.com/1821404/37778618-abedbab8-2dea-11e8-8094-41cd2177d338.png)](https://community.algolia.com/instantsearch-ios/examples.html#query-suggestions)

**Comment by spinach** [comment]
Actually there is one. Not sure why It didn't load in your case. If you still think there's an issue please re-open 👍 

![image](https://user-images.githubusercontent.com/1502519/38027332-92d6096e-328f-11e8-9d0e-aa4362156900.png)
