### ISSUE TITLE
Where should i give the JSON URL path which to load all the content just like image,  name and price

### ISSUE THREAD

**Issue by rajkumar0143** [algolia/instantsearch-ios-examples#8]

**Comment by spinach** [comment]
Hey @rajkumar0143 ,

Thank you for contacting us. In order to help you more, can you tell us a bit more about what you are trying to achieve? Some code sample or screenshot could help in understanding better what you are trying to achieve. 

Thanks!

**Comment by rajkumar0143** [comment]
I have URL path which contain Product name, image and price which to load in table view and then start filter instant search core swift  according  name,
The example given JSONObject but i didn't find where did you get content to display to in table view

**Comment by spinach** [comment]
Hey @rajkumar0143 ,

You can follow this guide [here](https://community.algolia.com/instantsearch-core-swift/guide/search.html) on how to display your content with instant search core. You can also use InstantSearch, here is the [getting started guide](https://community.algolia.com/instantsearch-ios/getting-started.html).
